-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["ivery_christmas_0"] = {{ name = "other", tiles = {"ivery_christmas_14",
"ivery_christmas_15"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
