require 'Items/ProceduralDistributions'
require 'Items/SuburbsDistributions'

-- Dawn
table.insert(ProceduralDistributions["list"]["GigamartToys"].items, "Base.DawnPlushie");
table.insert(ProceduralDistributions["list"]["GigamartToys"].items, 8);
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, "Base.DawnPlushie");
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateToys"].items, "Base.DawnPlushie");
table.insert(ProceduralDistributions["list"]["CrateToys"].items, 5);
table.insert(ProceduralDistributions["list"]["DaycareCounter"].items, "Base.DawnPlushie");
table.insert(ProceduralDistributions["list"]["DaycareCounter"].items, 2);
table.insert(ProceduralDistributions["list"]["DaycareShelves"].items, "Base.DawnPlushie");
table.insert(ProceduralDistributions["list"]["DaycareShelves"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "Base.DawnPlushie");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 1);
table.insert(ProceduralDistributions["list"]["WardrobeChild"].junk.items, "Base.DawnPlushie");
table.insert(ProceduralDistributions["list"]["WardrobeChild"].junk.items, 1);
table.insert(ProceduralDistributions["list"]["PrisonCellRandom"].junk.items, "Base.DawnPlushie");
table.insert(ProceduralDistributions["list"]["PrisonCellRandom"].junk.items, 2);
table.insert(SuburbsDistributions.all.inventorymale.items, "Base.DawnPlushie");
table.insert(SuburbsDistributions.all.inventorymale.items, 0.001);

-- DawnBaby
table.insert(ProceduralDistributions["list"]["GigamartToys"].items, "Base.DawnBaby");
table.insert(ProceduralDistributions["list"]["GigamartToys"].items, 1);
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, "Base.DawnBaby");
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, 0.01);
table.insert(ProceduralDistributions["list"]["CrateToys"].items, "Base.DawnBaby");
table.insert(ProceduralDistributions["list"]["CrateToys"].items, 1);
table.insert(ProceduralDistributions["list"]["DaycareCounter"].items, "Base.DawnBaby");
table.insert(ProceduralDistributions["list"]["DaycareCounter"].items, 0.005);
table.insert(ProceduralDistributions["list"]["DaycareShelves"].items, "Base.DawnBaby");
table.insert(ProceduralDistributions["list"]["DaycareShelves"].items, 0.005);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "Base.DawnBaby");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.005);
table.insert(ProceduralDistributions["list"]["WardrobeChild"].junk.items, "Base.DawnBaby");
table.insert(ProceduralDistributions["list"]["WardrobeChild"].junk.items, 0.005);
table.insert(ProceduralDistributions["list"]["PrisonCellRandom"].junk.items, "Base.DawnBaby");
table.insert(ProceduralDistributions["list"]["PrisonCellRandom"].junk.items, 0.01);
table.insert(SuburbsDistributions.all.inventoryfemale.items, "Base.DawnBaby");
table.insert(SuburbsDistributions.all.inventoryfemale.items, 0.001);